%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: Q:\OneDrive - The University of Colorado Denver\From Dropbox\STED\STED Data\230822\45nmYG_DyMINvsSTED\BarGraphResults\ROI1.csv
%
% Auto-generated by MATLAB on 18-Oct-2023 16:33:09

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 8);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["VarName1", "Area", "Mean", "StdDev", "Min", "Max", "IntDen", "RawIntDen"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
ROI8 = readtable("Q:\OneDrive - The University of Colorado Denver\From Dropbox\STED\STED Data\230822\45nmYG_DyMINvsSTED\BarGraphResults\ROI8.csv", opts);


%% Clear temporary variables
clear opts

%% Now calculate ratio of Confocal after/before for each roi, then find mean and std

conratios=zeros(9,5);
conratio_mean=zeros(5,1);
conratio_std=zeros(5,1);

for i=1:5
        conratio(1,i)=ROI1.Mean(2*i)/ROI1.Mean(2*i-1);
        conratio(2,i)=ROI2.Mean(2*i)/ROI2.Mean(2*i-1);
        conratio(3,i)=ROI3.Mean(2*i)/ROI3.Mean(2*i-1);
        conratio(4,i)=ROI4.Mean(2*i)/ROI4.Mean(2*i-1);
        conratio(5,i)=ROI5.Mean(2*i)/ROI5.Mean(2*i-1);
        conratio(6,i)=ROI6.Mean(2*i)/ROI6.Mean(2*i-1);
        conratio(7,i)=ROI7.Mean(2*i)/ROI7.Mean(2*i-1);
        conratio(8,i)=ROI8.Mean(2*i)/ROI8.Mean(2*1-1);
        conratio(9,i)=ROI9.Mean(2*i)/ROI9.Mean(2*i-1);
        conratio_mean(i,1)=mean(conratio(:,i));
        conratio_std(i,1)=std(conratio(:,i));
end
        
%% Now do bar graphs
% x = 1:13;
% data = [37.6 24.5 14.6 18.1 19.5 8.1 28.5 7.9 3.3 4.1 7.9 1.9 4.3]';
% errhigh = [2.1 4.4 0.4 3.3 2.5 0.4 1.6 0.8 0.6 0.8 2.2 0.9 1.5];
% errlow  = [4.4 2.4 2.3 0.5 1.6 1.5 4.5 1.5 0.4 1.2 1.3 0.8 1.9];
% 
% bar(x,data)                
% 
% hold on
% 
% er = errorbar(x,data,errlow,errhigh);    
% er.Color = [0 0 0];                            
% er.LineStyle = 'none';  
% 
% hold off


fig16=figure(16);
X = categorical({'DyMIN1','DyMIN2','DyMIN3','DyMIN4','STED'});
X = reordercats(X,{'DyMIN1','DyMIN2','DyMIN3','DyMIN4','STED'});
Y = conratio_mean;
b = bar(X,Y);
b.FaceColor = 'flat';
b.CData(5,:) = [0.5 0 0.5];
hold on
er = errorbar(X,Y,conratio_std,conratio_std); 
er.Color = [0 0 0];                            
er.LineStyle = 'none';  

ylabel("Counts in Confocal ROI after/before")

fig16.Units               = 'centimeters';
fig16.Position(3)         = 6;
fig16.Position(4)         = 5;
set(fig16.Children, ...
    'FontName',     'Times', ...
    'FontSize',     9);
set(gca,'LooseInset', max(get(gca,'TightInset'), 0.02))
fig16.PaperPositionMode   = 'auto';
print('Q:\OneDrive - The University of Colorado Denver\From Dropbox\STED\STED Data\230822\45nmYG_DyMINvsSTED\CONafterbeforeBar', '-dpng', '-r600')
